// module.exports = `### Hi there 👋
// **fireMan-34/fireMan-34** is a ✨ _special_ ✨ repository because its`+ " `README.md`" + ` (this file) appears on your GitHub profile.

// Here are some ideas to get you started:

// - 🔭 I’m currently working on ...
// - 🌱 I’m currently learning ...
// - 👯 I’m looking to collaborate on ...
// - 🤔 I’m looking for help with ...
// - 💬 Ask me about ...
// - 📫 How to reach me: ...
// - 😄 Pronouns: ...
// - ⚡ Fun fact: ...
// `
const { AUTHOR, BLOG_URL } = require('../config');
const aboutMeArray = [
    `# [Hello, I am ` + AUTHOR + `](${BLOG_URL})`,
    `- 🌱 I’m currently learning ...`,
]
module.exports = aboutMeArray.join('\n');